// Prarthan's portfolio chat worker (deployed as don-portfolio).
//
// The persona's facts live in worker/knowledge.md + worker/tweets.json,
// generated by `bun scripts/build-knowledge.mjs` (tweets via
// `bun scripts/import-tweets.mjs`). For the Cloudflare dashboard, paste the
// generated worker/worker.deploy.js (everything inlined) and set secrets in
// Settings → Variables & Secrets. See worker/README.md.
import knowledge from "./worker/knowledge.md";
import tweets from "./worker/tweets.json";

const DEFAULT_MODEL = "gemini-2.5-flash"; // 2.0-flash is shut down; set env GEMINI_MODEL to override

// Live tweet sync (SocialData.tools — 3 free req/min covers this easily)
const TWITTER_USER_ID = "1005519845075705857"; // override via env TWITTER_USER_ID
const TWITTER_SCREEN_NAME = "prarthandon"; // override via env TWITTER_SCREEN_NAME

const PERSONA = `You are "prarthan://ai" — the AI persona on Prarthan Agarwal's personal website (prarthanagarwal.com). You answer visitors' questions about Prarthan.
Voice: concise, friendly, a little witty — Feynman's curiosity in Chandler Bing's words. Plain text, short paragraphs; small bullet lists are fine. No markdown headers.
Rules:
- Stick to the facts below. Never invent projects, employers, roles, numbers, or links.
- Only share links that appear in the facts.
- If you don't know something, say so and suggest emailing Prarthan instead of guessing.
- If asked about hiring or availability: Prarthan is open to interesting freelance/contract work that fits — invite them to email him.
- If asked about anything unrelated to Prarthan, politely steer the conversation back to Prarthan.
- The tweets are his public voice; you may quote or reference them (with their dates) when relevant.`;

// Fetches his latest tweets + live profile from SocialData and caches in KV.
// Called by the cron trigger (scheduled) and as a bootstrap on first chat.
async function refreshTweets(env) {
  if (!env.TWEETS_KV || !env.TWEETS_API_KEY) return;
  const headers = {
    Authorization: `Bearer ${env.TWEETS_API_KEY}`,
    Accept: "application/json",
  };
  try {
    const res = await fetch(
      `https://api.socialdata.tools/twitter/user/${env.TWITTER_USER_ID || TWITTER_USER_ID}/tweets`,
      { headers },
    );
    if (res.ok) {
      const json = await res.json();
      const fresh = (json.tweets ?? [])
        .filter((t) => !t.retweeted_status) // skip retweets
        .map((t) => ({
          id: t.id_str,
          date: t.tweet_created_at,
          text: t.full_text ?? t.text ?? "",
        }))
        .filter((t) => t.text);
      if (fresh.length > 0) {
        await env.TWEETS_KV.put("tweets", JSON.stringify(fresh), {
          expirationTtl: 7 * 24 * 3600,
        });
      }
    }
    const prof = await fetch(
      `https://api.socialdata.tools/twitter/user/${env.TWITTER_SCREEN_NAME || TWITTER_SCREEN_NAME}`,
      { headers },
    );
    if (prof.ok) {
      const p = await prof.json();
      await env.TWEETS_KV.put(
        "profile",
        JSON.stringify({
          name: p.name,
          screen_name: p.screen_name,
          description: p.description,
          followers_count: p.followers_count,
          statuses_count: p.statuses_count,
        }),
        { expirationTtl: 7 * 24 * 3600 },
      );
    }
  } catch {
    // keep the previous snapshot; the next run will retry
  }
}

// Live KV tweets first (newest), then older bundled archive tweets (deduped).
function buildTweetLines(freshTweets) {
  const all = freshTweets?.length
    ? [...freshTweets, ...tweets.filter((t) => !freshTweets.some((f) => f.id === t.id))]
    : tweets;
  return all.length > 0
    ? all.map((t) => `${t.date} — ${t.text}`).join("\n")
    : "(No tweets available yet — set up the live sync or import your X archive.)";
}

function buildSystemInstruction(freshTweets, profile) {
  const profileLine = profile
    ? `\nLive X profile (@${profile.screen_name}): "${profile.description}" — ${profile.followers_count} followers, ${profile.statuses_count} tweets.`
    : "";
  return `${PERSONA}${profileLine}

=== FACTS ABOUT PRARTHAN ===
${knowledge}

=== TWEETS (newest first; live layer auto-refreshes ~every 30 min) ===
${buildTweetLines(freshTweets)}`;
}

// Best-effort in-memory per-IP rate limit (per isolate, not durable —
// see docs/rate-limit.md for the KV token-bucket upgrade path).
const WINDOW_MS = 60_000;
const MAX_PER_MIN = 20;
const hits = new Map();
function isLimited(ip) {
  const now = Date.now();
  const arr = (hits.get(ip) ?? []).filter((t) => now - t < WINDOW_MS);
  if (hits.size > 2000) {
    // prune stale entries so the map can't grow unbounded
    for (const [k, v] of hits) if (!v.length) hits.delete(k);
  }
  if (arr.length >= MAX_PER_MIN) {
    hits.set(ip, arr);
    return true;
  }
  arr.push(now);
  hits.set(ip, arr);
  return false;
}

export default {
  async fetch(request, env, ctx) {
    // Dynamic CORS: allow localhost during dev and the production domains
    const origin = request.headers.get("Origin") || "";
    const allowedOrigins = new Set([
      "https://prarthanagarwal.com",
      "https://www.prarthanagarwal.com",
      "http://localhost:3000",
    ]);
    const allowOrigin = allowedOrigins.has(origin) ? origin : "https://prarthanagarwal.com";
    const cors = {
      "Access-Control-Allow-Origin": allowOrigin,
      "Access-Control-Allow-Headers": "Content-Type, Accept",
      "Access-Control-Allow-Methods": "POST, OPTIONS",
    };

    if (request.method === "OPTIONS") {
      return new Response(null, { headers: cors });
    }
    if (request.method === "GET") {
      return new Response("OK", { headers: cors });
    }
    if (request.method !== "POST") {
      return new Response("Method Not Allowed", { status: 405, headers: cors });
    }

    const ip = request.headers.get("CF-Connecting-IP") || "unknown";
    if (isLimited(ip)) {
      return new Response("Too Many Requests", {
        status: 429,
        headers: { "Retry-After": "60", ...cors },
      });
    }

    let payload;
    try {
      payload = await request.json();
    } catch {
      return new Response("Invalid JSON", { status: 400, headers: cors });
    }

    // Fresh tweet layer from KV; fall back to the bundled archive snapshot
    let freshTweets = null;
    let profile = null;
    if (env.TWEETS_KV) {
      freshTweets = await env.TWEETS_KV.get("tweets", { type: "json" });
      profile = await env.TWEETS_KV.get("profile", { type: "json" });
      if (!freshTweets && env.TWEETS_API_KEY) {
        // Bootstrap: cache is empty, so refresh in the background while the
        // chat proceeds with the bundled snapshot.
        ctx?.waitUntil?.(refreshTweets(env));
      }
    }

    const { messages = [] } = payload;
    const contents = messages
      .filter((m) => m.content?.trim())
      .map((m) => ({
        role: m.isUser ? "user" : "model",
        parts: [{ text: m.content }],
      }));
    if (contents.length === 0) {
      return new Response("No messages provided", { status: 400, headers: cors });
    }

    const model = env.GEMINI_MODEL || DEFAULT_MODEL;
    const base = `https://generativelanguage.googleapis.com/v1beta/models/${model}`;
    const body = {
      systemInstruction: { parts: [{ text: buildSystemInstruction(freshTweets, profile) }] },
      contents,
      generationConfig: { temperature: 0.5, maxOutputTokens: 512 },
    };

    // Stream Gemini's SSE response straight through so the client renders progressively
    const sseUrl = `${base}:streamGenerateContent?alt=sse&key=${env.GEMINI_API_KEY}`;
    const upstream = await fetch(sseUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (!upstream.ok) {
      const text = await upstream.text();
      return new Response(text, { status: upstream.status, headers: cors });
    }

    const encoder = new TextEncoder();
    const stream = new ReadableStream({
      async start(controller) {
        try {
          const reader = upstream.body.getReader();
          const decoder = new TextDecoder();
          let buffer = "";
          let gotText = false;
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\n");
            buffer = lines.pop() ?? "";
            for (const line of lines) {
              if (!line.startsWith("data: ")) continue;
              const data = line.slice(6).trim();
              if (!data || data === "[DONE]") continue;
              let json;
              try {
                json = JSON.parse(data);
              } catch {
                continue;
              }
              const text =
                json?.candidates?.[0]?.content?.parts?.map((p) => p.text ?? "").join("") ?? "";
              if (text) {
                gotText = true;
                controller.enqueue(encoder.encode(text));
              }
            }
          }

          if (!gotText) {
            // Stream produced nothing (empty response / safety block) —
            // fall back to a one-shot generateContent call.
            const fallback = await fetch(`${base}:generateContent?key=${env.GEMINI_API_KEY}`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(body),
            });
            if (fallback.ok) {
              const json = await fallback.json();
              const text =
                json?.candidates?.[0]?.content?.parts?.map((p) => p.text ?? "").join("") ?? "";
              controller.enqueue(
                encoder.encode(text || "I couldn't come up with an answer — try asking differently."),
              );
            } else {
              controller.enqueue(encoder.encode("Something went wrong on my end. Try again in a moment."));
            }
          }
        } catch {
          // Stream died mid-way; the client keeps whatever it received.
          controller.enqueue(encoder.encode("\n[stream interrupted — please try again]"));
        } finally {
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        ...cors,
      },
    });
  },

  // Cron trigger (dashboard: Settings → Triggers → Cron Triggers, */30 * * * *)
  async scheduled(event, env) {
    await refreshTweets(env);
  },
};
